require: rubocop-rails

AllCops:
  NewCops: enable

  Exclude:
      - '.git/**/*'
      - 'bin/bundle'
      - 'node_modules/**/*'
      - 'tmp/**/*'
      - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SymbolArray:
  Enabled: false
