require: rubocop-rails

AllCops:
  NewCops: enable

  SuggestExtensions: false

  Exclude:
      - '.git/**/*'
      - 'bin/bundle'
      - 'config/initializers/*'
      - 'node_modules/**/*'
      - 'db/schema.rb'
      - 'tmp/**/*'
      - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/SymbolArray:
  Enabled: false
